import { register } from './registry.js';
import { composeDispose } from '../plugin-contract.js';
import { isSafeImgUrl } from '../safe-url.js';
import { buildPreviewHtml } from '../store-template-preview.js';
import { mediaPlaceholder } from '../media-placeholder.js';
import { webEmbedFields, webEmbedDefaults, sandboxTokens } from '../web-embed-fields.js';

// Embed / Web widget, the ONE iframe-isolated widget class. External URLs OR
// inline HTML (srcdoc) generated by an AI agent are sandboxed so untrusted
// content can't touch the rest of the slide. Native widgets render directly;
// only this one is isolated, by design.

// Mode fallback shared by schema showIfs and render(): legacy content stored
// before the mode select existed has no `mode` key but may carry `html` — it
// must keep resolving to srcdoc (see renderNotes contract).
const modeOf = c => c.mode ?? (c.html ? 'srcdoc' : 'url');
const isUrlMode = c => modeOf(c) === 'url';
const isSrcdocMode = c => modeOf(c) === 'srcdoc';

// Build the `:root{…}` CSS-variable block for 'Match slide theme'. Values are
// read from the widget's computed style (slide themes / brand kits set them as
// inherited custom properties on the slide root) and sanitised so a value can
// never break out of the injected <style> element or its declaration block.
function themeVarsCss(el) {
  const cs = getComputedStyle(el);
  const read = (name, fallback) => {
    const v = String(cs.getPropertyValue(name) || '').trim().replace(/[<>{};]/g, '');
    return v || fallback;
  };
  return ':root{'
    + `--bb-st-bg:${read('--bb-st-bg', '#0a0a10')};`
    + `--bb-st-fg:${read('--bb-st-fg', '#f1f1f4')};`
    + `--bb-st-accent:${read('--bb-st-accent', '#8b5cf6')};`
    + '}';
}

// Insert the theme <style> EARLY (right after <head>, or after the doctype,
// or prepended) so the document's own rules still win — the injection is a
// fallback the AI dashboard can consume via var(--bb-st-…), never an override.
// Inserting after the doctype (not before it) keeps standards mode intact.
function injectThemeStyle(html, css) {
  const tag = `<style>${css}</style>`;
  const head = /<head[^>]*>/i.exec(html);
  if (head) {
    const at = head.index + head[0].length;
    return html.slice(0, at) + tag + html.slice(at);
  }
  const doctype = /^\s*<!doctype[^>]*>/i.exec(html);
  if (doctype) return html.slice(0, doctype[0].length) + tag + html.slice(doctype[0].length);
  return tag + html;
}

export default register({
  type: 'embed',
  label: 'Embed / Web',
  group: 'media',
  icon: '🧩',
  network: true,
  schemaVersion: 1,
  defaults: () => ({
    mode: 'url', html: '',
    background: '#0a0a10', scale: 100, injectTheme: true,
    lockInteraction: true,
    // Shared web-embed keys: url, reloadSec, sandbox, allowForms, allowPopups.
    ...webEmbedDefaults(),
  }),
  schema: () => {
    // Shared url/reloadSec/sandbox/permission fields (canonical labels, help,
    // validate) — distributed by key across the sections below so the wording
    // can't drift from iframe.js. URL-mode-only fields are gated; the sandbox
    // and permission toggles apply to BOTH modes.
    const wef = Object.fromEntries(webEmbedFields({ showIf: isUrlMode }).map(f => [f.key, f]));
    return {
      fields: [
        { type: 'section', label: 'Content', key: 'content' },
        { key: 'mode', type: 'select', label: 'Source', buttons: true, options: [
          { value: 'url', label: 'External URL' },
          { value: 'srcdoc', label: 'Inline HTML (AI agent)' },
        ] },
        wef.url,
        { key: 'html', type: 'code', label: 'Inline HTML',
          showIf: isSrcdocMode,
          placeholder: '<!doctype html>\n<html>\n<head>\n  <style>body { margin: 0; }</style>\n</head>\n<body>\n  …\n</body>\n</html>',
          help: 'Loaded into a sandboxed (allow-scripts, opaque-origin) iframe via srcdoc, ideal for AI-generated dashboards.' },

        { type: 'section', label: 'Appearance', key: 'appearance' },
        { key: 'scale', type: 'number', label: 'Zoom', min: 25, max: 400, step: 5, slider: true, suffix: '%',
          showIf: isUrlMode, tier: 'advanced',
          help: 'Scale the embedded page to fit the widget, useful for desktop-sized pages on portrait screens.' },
        { key: 'background', type: 'color', label: 'Background', clearable: true, tier: 'advanced',
          help: 'Shown behind transparent pages; × resets to the default dark.' },
        { key: 'injectTheme', type: 'toggle', label: 'Match slide theme',
          showIf: isSrcdocMode, tier: 'advanced',
          help: 'Prepends the slide theme’s colours as CSS variables (--bb-st-bg, --bb-st-fg, --bb-st-accent) so AI-generated dashboards can match the theme and brand kit. The HTML’s own styles still win.' },

        { type: 'section', label: 'Behavior', key: 'behavior', showIf: isUrlMode },
        { ...wef.reloadSec, tier: 'advanced' },

        { type: 'section', label: 'Advanced', key: 'advanced', collapsed: true,
          summary: c => c.sandbox === false ? '⚠️ sandbox off' : '✓' },
        { ...wef.sandbox, tier: 'advanced' },
        { ...wef.allowForms, tier: 'advanced' },
        { ...wef.allowPopups, tier: 'advanced' },
        { key: 'lockInteraction', type: 'toggle', label: 'Lock interaction', tier: 'advanced',
          help: 'Blocks touch and mouse input on the embedded page so viewers on touch screens can’t tap links and navigate it away. Turn off only for interactive kiosks.' },
      ],
    };
  },
  render(slide, container) {
    const c = slide.content ?? {};
    const mode = modeOf(c);
    // URL mode only accepts http(s) / relative; srcdoc is sandbox-isolated by
    // design so any HTML is allowed there. A `javascript:` URL falls through to
    // the empty-state rather than navigating the player.
    const hasContent = mode === 'srcdoc' ? !!c.html : isSafeImgUrl(c.url);

    if (!hasContent) {
      const empty = mediaPlaceholder({ icon: '🧩', message: 'Embed widget, paste a URL or supply an AI agent\'s inline HTML.' });
      container.appendChild(empty);
      return composeDispose(() => empty.remove());
    }

    // Wrapper stays class-less on purpose: .bb-slide would add the theme's
    // slide padding, and embeds must keep filling their slot edge-to-edge.
    const root = document.createElement('div');
    root.style.cssText = 'position:relative;width:100%;height:100%;overflow:hidden;';

    const f = document.createElement('iframe');
    f.dataset.field = 'mode url html injectTheme scale background reloadSec';
    // `||` (not `??`) so the clearable colour's empty string falls back to the
    // default dark instead of producing invalid `background:;` CSS.
    const bg = c.background || '#0a0a10';
    // Zoom via CSS transform (URL mode only): the iframe renders at logical px,
    // then scales back to fit the widget box. width/height inversely sized so
    // the page believes it has more (or less) room than the box — same
    // technique as iframe.js, clamped in render as defense-in-depth.
    const scale = mode === 'url' ? Math.max(25, Math.min(400, Number(c.scale) || 100)) / 100 : 1;
    f.style.cssText = scale !== 1
      ? `width:${100 / scale}%;height:${100 / scale}%;border:0;background:${bg};transform:scale(${scale});transform-origin:top left;`
      : `width:100%;height:100%;border:0;background:${bg};`;
    f.referrerPolicy = 'no-referrer';
    // Sandbox tokens come from sandboxTokens() (shared/web-embed-fields.js) —
    // the ONE place the token string is assembled. THE INVARIANT: NEVER grant
    // 'allow-same-origin'. Kept minimal per mode:
    //   url    → 'allow-scripts' (+ opted-in allow-forms / allow-popups) ONLY.
    //            Granting allow-same-origin to a remote page lets it reach back
    //            into OUR origin (same-origin DOM, storage, cookies) and
    //            effectively neuters the sandbox, a sandbox-escape. Scripts
    //            alone are enough for dashboards.
    //   srcdoc → already an opaque (null) origin, so 'allow-same-origin' would
    //            only let the inline doc talk to ITSELF; we keep scripts only
    //            so it can't reach our storage/cookies either.
    // Permission toggles only ever ADD harmless tokens on top of
    // 'allow-scripts' — never replace this approach.
    const sandbox = sandboxTokens(c);
    if (sandbox) f.setAttribute('sandbox', sandbox);
    if (mode === 'srcdoc') {
      // Store-template embeds carry `slots` (edited JSON per data-slot key) and
      // `slotDefs`. When present, render a network-free preview: edited values
      // are injected so `{{slot:KEY.readUrl}}`-driven templates show them live
      // in the editor (see shared/store-template-preview.js). Plain inline-HTML
      // embeds (no slots) pass straight through.
      const html = String(c.html ?? '');
      let doc = (c.slots && Object.keys(c.slots).length && /\{\{\s*slot:/.test(html))
        ? buildPreviewHtml(html, c.slots)
        : html;
      // 'Match slide theme': inject the slide's CSS variables AFTER the slot
      // preview is built so the final document gets them. Truthy check (not
      // !== false) keeps legacy srcdoc content byte-identical.
      if (c.injectTheme) doc = injectThemeStyle(doc, themeVarsCss(container));
      f.srcdoc = doc;
    } else {
      f.src = c.url;
    }
    root.appendChild(f);

    // Interaction lock (default on): a transparent shield above the iframe so
    // touch-screen kiosks can't tap links and navigate the embedded dashboard
    // away. Pointer events stop here; the iframe never sees them.
    if (c.lockInteraction !== false) {
      const shield = document.createElement('div');
      shield.style.cssText = 'position:absolute;inset:0;background:transparent;';
      root.appendChild(shield);
    }
    // Title overlay, same affordance as the media-group siblings (image/video).
    if (slide.title) {
      const t = document.createElement('div');
      t.className = 'bb-image-title';
      t.textContent = slide.title;
      root.appendChild(t);
    }
    container.appendChild(root);
    let reloadTimer = null;
    if (mode === 'url') {
      // Auto-reload for status pages / dashboards. The 5 s floor protects the
      // player from reload storms — surfaced in the shared field's help+validate.
      const reloadMs = Math.max(0, Number(c.reloadSec) || 0) * 1000;
      if (reloadMs >= 5000) reloadTimer = setInterval(() => { f.src = c.url; }, reloadMs);
    }
    return composeDispose(() => {
      if (reloadTimer) clearInterval(reloadTimer);
      f.removeAttribute('src'); f.removeAttribute('srcdoc'); root.remove();
    });
  },
});
