import { register } from './registry.js';
import { composeDispose } from '../plugin-contract.js';
import { isSafeImgUrl } from '../safe-url.js';
import { buildPreviewHtml } from '../store-template-preview.js';

// Embed / Web widget, the ONE iframe-isolated widget class. External URLs OR
// inline HTML (srcdoc) generated by an AI agent are sandboxed so untrusted
// content can't touch the rest of the slide. Native widgets render directly;
// only this one is isolated, by design.

export default register({
  type: 'embed',
  label: 'Embed / Web',
  group: 'media',
  icon: '🧩',
  network: true,
  schemaVersion: 1,
  defaults: () => ({ mode: 'url', url: '', html: '', sandbox: true, background: '#0a0a10', reloadSec: 0 }),
  schema: () => ({
    fields: [
      { key: 'mode', type: 'select', label: 'Source', options: [
        { value: 'url', label: 'External URL' },
        { value: 'srcdoc', label: 'Inline HTML (AI agent)' },
      ] },
      { key: 'url', type: 'url', label: 'Web URL', test: 'embed',
        showIf: c => (c.mode ?? 'url') === 'url',
        help: 'Many sites block iframe embedding (X-Frame-Options/CSP). Keep Sandbox on for unknown sources.' },
      { key: 'reloadSec', type: 'duration', label: 'Reload every (0 = never)', min: 0, default: 0,
        showIf: c => (c.mode ?? 'url') === 'url',
        help: 'Refresh the page on a timer so embedded dashboards / status pages stay live.' },
      { key: 'html', type: 'code', label: 'Inline HTML',
        showIf: c => (c.mode ?? 'url') === 'srcdoc',
        help: 'Loaded into a sandboxed (allow-scripts, opaque-origin) iframe via srcdoc, ideal for AI-generated dashboards.' },
      { key: 'sandbox', type: 'toggle', label: 'Sandbox (allow-scripts)',
        help: '⚠️ On = scripts only, isolated from the player (no same-origin access). Off = the embedded page can navigate the whole player away, open popups, and trigger downloads. Only disable for fully trusted internal URLs.' },
      { key: 'background', type: 'color', label: 'Background' },
    ],
  }),
  render(slide, container) {
    const c = slide.content ?? {};
    const mode = c.mode ?? (c.html ? 'srcdoc' : 'url');
    // URL mode only accepts http(s) / relative; srcdoc is sandbox-isolated by
    // design so any HTML is allowed there. A `javascript:` URL falls through to
    // the empty-state rather than navigating the player.
    const hasContent = mode === 'srcdoc' ? !!c.html : isSafeImgUrl(c.url);

    if (!hasContent) {
      const empty = document.createElement('div');
      empty.style.cssText = 'display:flex;align-items:center;justify-content:center;width:100%;height:100%;background:#0a0a10;color:rgba(255,255,255,.5);text-align:center;padding:24px;font-family:var(--bb-font, Inter, sans-serif);';
      empty.innerHTML = '<div><div style="font-size:48px;opacity:.5;margin-bottom:8px;">🧩</div><div>Embed widget, paste a URL or supply an AI agent\'s inline HTML.</div></div>';
      container.appendChild(empty);
      return composeDispose(() => empty.remove());
    }

    const f = document.createElement('iframe');
    f.style.cssText = `width:100%;height:100%;border:0;background:${c.background ?? '#0a0a10'};`;
    f.referrerPolicy = 'no-referrer';
    // Sandbox tokens, kept minimal per mode:
    //   url    → 'allow-scripts' ONLY. Granting allow-same-origin to a remote
    //            page lets it reach back into OUR origin (same-origin DOM,
    //            storage, cookies) and effectively neuters the sandbox, a
    //            sandbox-escape. Scripts alone are enough for dashboards.
    //   srcdoc → already an opaque (null) origin, so 'allow-same-origin' would
    //            only let the inline doc talk to ITSELF; we keep scripts only
    //            so it can't reach our storage/cookies either.
    if (c.sandbox !== false) f.setAttribute('sandbox', 'allow-scripts');
    if (mode === 'srcdoc') {
      // Store-template embeds carry `slots` (edited JSON per data-slot key) and
      // `slotDefs`. When present, render a network-free preview: edited values
      // are injected so `{{slot:KEY.readUrl}}`-driven templates show them live
      // in the editor (see shared/store-template-preview.js). Plain inline-HTML
      // embeds (no slots) pass straight through.
      const html = String(c.html ?? '');
      f.srcdoc = (c.slots && Object.keys(c.slots).length && /\{\{\s*slot:/.test(html))
        ? buildPreviewHtml(html, c.slots)
        : html;
    } else {
      f.src = c.url;
    }
    container.appendChild(f);
    let reloadTimer = null;
    if (mode === 'url') {
      const reloadMs = Math.max(0, Number(c.reloadSec) || 0) * 1000;
      if (reloadMs >= 5000) reloadTimer = setInterval(() => { f.src = c.url; }, reloadMs);
    }
    return composeDispose(() => {
      if (reloadTimer) clearInterval(reloadTimer);
      f.removeAttribute('src'); f.removeAttribute('srcdoc'); f.remove();
    });
  },
});
